### ISSUE TITLE
Interference caused by using --debug-mem Grid flag

### ISSUE THREAD

**Issue by nelsonlachini** [aportelli/Hadrons#17]
Hadrons memory management 'sees' different sizes for objects depending whether `--debug-mem` is used or not. An example is the "memory needed" Hadrons message compared between 2 identical runs differing by the use of `--debug-mem`:
Without `--debug-mem`:
`Hadrons : Message  : 0.748221 s : Schedule (memory needed: 79.3 MB):`
With `--debug-mem`:
`Hadrons : Message  : 0.849924 s : Schedule (memory needed: 1.4 GB):`

**Comment by aportelli** [comment]
Fixed in fd36267
