### ISSUE TITLE
More complicated baryons are computed wrongly in Hadrons

### ISSUE THREAD

**Issue by felixerben** [aportelli/Hadrons#29]
In the first version of Baryon.hpp, which has been part of Hadrons until now, there was a bug regarding baryons which have an interpolator that is a linear combination of two or more quark combinations (like the sigma^0, lambda, ...). The problem is that the quark content is not passed in the correct (shuffled) order to the Grid function in lines 256-261:

                for (int iQ1 = 0; iQ1 < nQ; iQ1++){
                    for (int iQ2 = 0; iQ2 < nQ; iQ2++){
                        BaryonUtils<FIMPL>::ContractBaryons_Sliced(q1[t],q2[t],q3[t],gAl,gBl,gAr,gBr,quarks[iQ1].c_str(),quarks[iQ2].c_str(),parity,ch);
                        cs += prefactors[iQ1]*prefactors[iQ2]*ch;
                    }
                }

'Simple' baryons like nucleon, omega, sigma^+/-, Delta, etc. are not affected.

This issue will be solved with Raoul's pull request which will probably me merged into develop soon.

**Comment by aportelli** [comment]
Thanks, solved by #27
