### ISSUE TITLE
HDF5-related errors when compiling on Skylake at Cambridge

### ISSUE THREAD

**Issue by daschaich** [aportelli/Hadrons#33]
I'm afraid I've had zero luck compiling Grid+Hadrons for [the Skylake cluster at Cambridge](https://www.hpc.cam.ac.uk/systems/peta-4) over the past couple of weeks, and with Tuesday's DiRAC technical case deadline approaching I need to ask for help.  Back in [Grid issue 175](https://github.com/paboyle/Grid/issues/175#issuecomment-421830307) @aportelli mentioned building successfully at Cambridge, so I'm hoping there may be some world-readable build there from which I could copy workable options and module choices.  I have tried to divine some of this from CI builds like [this one](https://ci.cliath.ph.ed.ac.uk/viewLog.html?buildId=34729&buildTypeId=GridBasedSoftware_GridBuildAvx512DoubleMpiautoIntel19&tab=buildLog&branch_GridBasedSoftware_Grid=%3Cdefault%3E&_focus=285#_state=284), so far without success.

I've had several dozen builds fail on this system over the past couple of weeks.  In case it might be helpful, I attach some logs from my latest attempt, which fails with the HDF5-related errors mentioned in the subject.  (Grid's `make check` returns an error code but all the tests seem to say they're OK, which is why I'm opening this under Hadrons rather than Grid.)

From these logs I quote:

Grid commit:
> commit: 7cf7f11e
> branch: develop

Hadrons commit:
> HADRONS_BRANCH='develop'
> HADRONS_SHA='82ffe4f24a0684c37598440290f35c0b33d10b58'

Grid configure line:
> $ /home/dc-scha3/dev/Grid-Sky/configure --prefix=/home/dc-scha3/dev/Grid-Sky/install --with-lime=/home/dc-scha3/dev/c-lime-Sky/install --enable-precision=double --enable-simd=AVX512 --enable-comms=mpi3 --enable-mkl CC=mpiicc CXX=mpiicpc CXXFLAGS="-std=c++11 -qoverride-limits"

Full CPU description:
> $ cat /proc/cpuinfo | grep 'model name' | uniq
> model name      : Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz

Full compiler (for this latest attempt):
> $ mpiicpc -v | grep -v Copyright
> mpiicpc for the Intel(R) MPI Library 2019 Update 3 for Linux*
> icpc version 19.0.3.192 (gcc version 8.4.0 compatibility)

For obvious reasons I've made many attempts to try to use what look like the most promising of the 45 different hdf5 modules on offer at Cambridge.  The attached messy notes summarize the main ways these attempts have failed.  Typically I get either
> HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
>  #000: H5T.c line 1712 in H5Tcopy(): not a datatype or dataset
>    major: Invalid arguments to routine
>    minor: Inappropriate type

in Grid's `make check` or the undefined references in the attached Hadrons `make` log, in both cases with warnings about
> ld: warning: libhdf5.so.8, needed by /lib/../lib64/libhdf5_cpp.so, may conflict with libhdf5.so.103

Google hasn't yet helped me with that.

Thanks in advance for any hints you may be able to offer.

Attachments:
[build_script.txt](https://github.com/aportelli/Hadrons/files/4998030/build_script.txt)
[build_notes.txt](https://github.com/aportelli/Hadrons/files/4998031/build_notes.txt)
[module_list.txt](https://github.com/aportelli/Hadrons/files/4998043/module_list.txt)
[Grid_config.log](https://github.com/aportelli/Hadrons/files/4998032/Grid_config.log)
[grid.configure.summary.txt](https://github.com/aportelli/Hadrons/files/4998034/grid.configure.summary.txt)
[Grid_make.log](https://github.com/aportelli/Hadrons/files/4998035/Grid_make.log)
[Grid_make-install.log](https://github.com/aportelli/Hadrons/files/4998036/Grid_make-install.log)
[Grid_make-check.log](https://github.com/aportelli/Hadrons/files/4998037/Grid_make-check.log)
[Hadrons_config.log](https://github.com/aportelli/Hadrons/files/4998039/Hadrons_config.log)
[Hadrons_make.log](https://github.com/aportelli/Hadrons/files/4998040/Hadrons_make.log)
[Grid_make-check-old-HDF5.log](https://github.com/aportelli/Hadrons/files/4998041/Grid_make-check-old-HDF5.log)

**Comment by aportelli** [comment]
Hi David,

I'm afraid there is no real issue here with Hadrons' code as you are experiencing a linking error against HDF5 (not a compile one). This is an issue related to the HDF5 binaries you are using.

Let me try to help nonetheless. This linking error is typical of mixing C++11 binaries built with different compilers. Compilers tends to implicitly hide C++11 standard library function in some name space generally called `__cxx11` or `__1`. If a library was compiled with one convention and linked against another with the other convention then the symbol names don't match and linking fail, which I believe is what you are experiencing.

This is unfortunately a widespread issue, typically with compiler versions dating from the time C++11 was implemented. Things tend to be much more consistent with more recent versions.

In this kind of case I just compile myself HDF5 with the same compiler than Grid/Hadrons and it is generally fine. HDF5 is very easy to compile.

**Comment by daschaich** [comment]
> In this kind of case I just compile myself HDF5 with the same compiler than Grid/Hadrons and it is generally fine. HDF5 is very easy to compile.

Thanks, that's the kind of hint I was hoping for.  I'll attempt that and report how it goes.  In the meantime, I should probably reiterate that HDF5 linking wasn't the only issue I encountered, just the (hopefully) only one that's left after (I believe) I worked around all the others (some of which seem to be at play in [Grid issue 302](https://github.com/paboyle/Grid/issues/302)).  For example, Hadrons apparently failing to pick up compilation flags from `--with-grid=<dir>` may be more relevant to this repo.

**Comment by daschaich** [comment]
Very good, after just a couple more rounds the attached procedure gives me something that runs.  The `make check`s still complain, but I'll ignore that for now.  Thanks again.

[build_script.txt](https://github.com/aportelli/Hadrons/files/5004457/build_script.txt)
