### ISSUE TITLE
Intel compiler

### ISSUE THREAD

**Issue by joelgiedt** [aportelli/Hadrons#34]
Hi, We had to make some modifications to
Hadrons/Modules/MContraction/Baryon.hpp
The intel compiler wanted the last argument to regex_replace to be wrapped in a std::string().
For example:
gammaString = regex_replace(gammaString, std::regex("j12"),std::string("(Identity SigmaXZ)"));

**Comment by joelgiedt** [comment]
I gave up on the Intel compiler.  Too many problems.

**Comment by aportelli** [comment]
I am not a big fan either, clang is much more reliable. But still we have a CI compile successfully, without any hacks, for Intel 18 and Intel 19? Is that issues you got with Intel 20? (I have never tried).
