### ISSUE TITLE
Change of compile flags

### ISSUE THREAD

**Issue by JPRichings** [aportelli/Hadrons#49]
Not so much of an issue but a health warning both @felixerben and myself have found that compiling with clang-10 and clang-11 will fail if you do not add  CXXFLAGS=-pthread to hadrons on compile when building on laptops.

Open questions:

1) Was there a change in the configure script?
2) This seems to be limited to laptop compiles. Why?

**Comment by aportelli** [comment]
No there was no change regarding that. It sounds like OS dependent or potentially on your specific clang installation. It is not necessary on Tesseract or my laptop (macOS).
