### ISSUE TITLE
MIO::LoadBinary does not check for lattice size

### ISSUE THREAD

**Issue by fjosw** [aportelli/Hadrons#96]
Tobi noticed that the `MIO::LoadBinary` module does not check whether the file fits the lattice geometry. If Hadrons is run with a grid that is smaller than the configuration in the file it does not throw any error or warning. As the binary file format does not contain metadata like the plaquette, there is no check within Grid.

A simple solution would be to check the file size against the expected size based on the lattice geometry within `MIO::LoadBinary`.

**Comment by aportelli** [comment]
`MIO::LoadBinary` is unsafe as it is just raw binary, and is not intended to be safe. It does display checksums in the log but they would have to be checked manually against another source.

Maybe I should just discontinue it or display a warning, it is available for convenience in case somebody has to deal with a raw Grid binary dump not wrapped in metadata. `LoadField` and `SaveField` do wrap in metadata and have a strict checksum verification when loading, which should detect any possible issues. Checksums are enough and safer than data-specific checks like geometry and plaquette (which cannot guarantee the file is not corrupted).

**Comment by aportelli** [comment]
Closing

**Comment by aportelli** [comment]
Closing
